// Listagem de todos os compositores e suas informações
exports.compositoresListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composers List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Bio</th><th>Birth</th><th>Death</th><th>Period</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].bio}</td>
                    <td>${slist[i].dataNasc}</td>
                    <td>${slist[i].dataObito}</td>
                    <td><a href="/periodos/${slist[i].periodo}">${slist[i].periodo}</a></td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// Formulário para registo de um novo compositor
exports.compositoresFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composers Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="bio" required/>
                        <label>Birth</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" required/>
                        <label>Death</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" required/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" required/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

// Formulário para edição de um compositor
exports.compositoresFormEditPage = function(compositor, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composers Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${compositor.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${compositor.nome}"/>
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${compositor.bio}"/>
                        <label>Birth</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${compositor.dataNasc}"/>
                        <label>Death</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${compositor.dataObito}"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${compositor.periodo}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// Formulário com informações de um compositor após sua edição
exports.compositoresPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Número: </b> ${compositor.id}</li>
                    <li><b>Biografia: </b> ${compositor.bio}</a></li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Período: </b> <a href="/periodos/${compositor.periodo}">${compositor.periodo}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            </ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por compositor::RPCW2022 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// Listagem de todos os períodos 
exports.periodsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers Periods</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composers Periods</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Type of Period</th>
                        </tr>
                `
                let uniquePeriods = new Set();
                for(let i=0; i < slist.length ; i++){
                    uniquePeriods.add(slist[i].periodo);
                }
                
                uniquePeriods.forEach(periodo => {
                    pagHTML += `
                            <tr>
                                <td>
                                    <a href="periodos/${periodo}">${periodo}</a>
                                </td>
                            </tr>
                    `
                });

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// Formulário que apresenta os compositores de um determinado período
exports.periodsPage = function(periodo, compositores, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${periodo}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo ${periodo}</h1>
            </header>

            <div class="w3-container">
                <table class="w3-table-all">
                <tr>
                    <th>Id</th><th>Name</th><th>Bio</th><th>Birth</th><th>Death</th><th>Period</th>
                    <th>Actions</th>
                </tr>
    `
    for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                    <tr>
                    <td>${compositores[i].id}</td>
                    <td>
                        <a href="/compositores/${compositores[i].id}">
                            ${compositores[i].nome}
                        </a>
                    </td>
                    <td>${compositores[i].bio}</td>
                    <td>${compositores[i].dataNasc}</td>
                    <td>${compositores[i].dataObito}</td>
                    <td><a href="/periodos/${compositores[i].periodo}">${compositores[i].periodo}</a></td>
                    <td>
                        [<a href="/compositores/edit/${compositores[i].id}">Edit</a>][<a href="/compositores/delete/${compositores[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }
    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <address>Gerado por compositor::RPCW2022 em ${d} - [<a href="/periodos">Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}